version: '3'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
    - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  chargement:
    build: ./chargement
    depends_on:
      - elasticsearch
    container_name: chargement
    networks:
      - es-net
    volumes:
      - shared-data:/data
    command: ["/usr/bin/wait-for-it.sh", "es-container:9200", "--", "python", "executor.py"]

  ml-processing:
    build: ./ML
    depends_on:
      - elasticsearch
      - chargement
    container_name: ml-processing
    networks:
      - es-net
    volumes:
      - shared-data:/data
    command: ["bash", "-c", "while [ ! -f /data/chargement_done.txt ]; do echo 'Waiting for chargement to complete...'; sleep 15; done; /app/run_all.sh"]

networks:
  es-net:
    driver: bridge

volumes:
  es-data:
    driver: local
  shared-data:
    driver: local