name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Build and start services
        run: |
          docker-compose up --build -d

      - name: Wait for API to be ready
        run: |
          until curl -f http://localhost:8000/; do
            echo "Waiting for API to be available..."
            sleep 5
          done

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run API Tests
        run: |
          pytest tests/test_api.py --disable-warnings

      - name: Shut down Docker Compose services
        if: always()
        run: |
          docker-compose down
